### ISSUE TITLE
cat: /tmp/fluxspace/ip_hits: No such file or directory. Captive Portal error all of a sudden

### ISSUE THREAD

**Issue by drjohannspector** [FluxionNetwork/fluxion#305]
#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes

#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behaviour?
captive portal interface does not start, 
iwconfig output shows both interfaces in monitor mode.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
select handshake, select interface, disconnected, no ssl, choose spoofed ap page.....

#### What do you think the expected behaviour should be?
captive portal should start with the fake ap. iwconfig output shows FXan0AP as monitor as well as wlan0.

#### Specs

root@kali:~/stuff/fluxion/scripts# ./diagnostics.sh wlan0
[ FLUXION Info ]
grep: fluxion.sh: No such file or directory
FLUXION V.

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy0
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT3572
Injection Test: No Answer...

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.10-1kali2 (2017-11-08)

-----

Not sure how this was working perfectly for me all day and suddenly does not work any longer. I removed the fluxion folder, cloned it again to see if it would fix it, now I see the missing fluxspace error below when I try to start captive portal. It would just hang at starting captive portal, now I am also seeing the missing file/directories.

[*] Select a captive portal interface for the rogue network.

                                   ESSID: tweedledee / WPA2                                                
                                 Channel: 52                                                               
                                   BSSID: A0:04:60:8A:33:F4 (UNKNOWN)                                 

                       [01] Generic Portal                                   Arabic                       
                       [02] Generic Portal                                Bulgarian                       
                       [03] Generic Portal                                  Chinese                       
                       [04] Generic Portal                                    Czech                       
                       [05] Generic Portal                                   Danish                       
                       [06] Generic Portal                                    Dutch                       
                       [07] Generic Portal                                  English                       
                       [08] Generic Portal                                   French                       
                       [09] Generic Portal                                   German                       
                       [10] Generic Portal                                    Greek                       
                       [11] Generic Portal                                   Hebrew                       
                       [12] Generic Portal                                Hungarian                       
                       [13] Generic Portal                               Indonesian                       
                       [14] Generic Portal                                  Italian                       
                       [15] Generic Portal                                Norweigan                       
                       [16] Generic Portal                                   Polish                       
                       [17] Generic Portal                               Portuguese                       
                       [18] Generic Portal                                 Romanian                       
                       [19] Generic Portal                                  Russian                       
                       [20] Generic Portal                                  Serbian                       
                       [21] Generic Portal                                   Slovak                       
                       [22] Generic Portal                                Slovenian                       
                       [23] Generic Portal                                  Spanish                       
                       [24] Generic Portal                                     Thai                       
                       [25] Generic Portal                                  Turkish                       
                       [26] *                                                     *                       
                       [27] Back                                                                   

[fluxion@kali]-[~] 7

cat: /tmp/fluxspace/ip_hits: No such file or directory
cat: '"/tmp/fluxspace/ip_hits"': No such file or directory
[*] Starting Captive Portal access point service...

**Comment by drjohannspector** [comment]
Captive portal on 5g just shows:
cat: /tmp/fluxspace/ip_hits: No such file or directory
cat: '"/tmp/fluxspace/ip_hits"': No such file or directory
[*] Starting Captive Portal access point service...

While captive portal on a 2.4g network only shows:
cat: /tmp/fluxspace/ip_hits: No such file or directory
the AP seems to start normally after the ip_hits error.....what is happening here? Seems out of the blue late this evening, this was before updating to the new master though. When I removed fluxion to attempt a fix for captive portal not starting, all I did was remove the cloned git folder, I did not run --purge or remove any files outside of the fluxion directory, which was in /root

**Comment by deltaxflux** [comment]
Fixed in latest version.

**Comment by drjohannspector** [comment]
I am still seeing this when starting captive portal:

[fluxion@kali]-[~] 50

cat: /tmp/fluxspace/ip_hits: No such file or directory
[*] Starting Captive Portal access point service...



It hangs there and never opens any xterm windows.
