### ISSUE TITLE
MDK4 not found, AP jammer service not working, can't connect manually to the fake AP, Fake AP not visible on mobile phone

### ISSUE THREAD

**Issue by mofox** [FluxionNetwork/fluxion#555]
#### Summary
**AP Jammer not working properly or at all**
**Can't connect to the fake AP**

[*] Starting Captive Portal access point service...
[*] Starting Captive Portal access point routes...
[*] Starting access point DHCP service as daemon...
[*] Starting access point DNS service as daemon...
[*] Starting access point captive portal as daemon...
[*] Starting access point jammer as daemon...
**####/root/fluxion/attacks/Captive Portal/attack.sh: line 1469: hash: mdk4: not found**
[*] Starting authenticator script...

#### What is the current behaviour?

- AP Jammer service not working.
  - Win7 client doesn't get disconnected and can't connect to the fake AP manually if browser is already launched
  - Win7 client doesn't get disconnected but sometimes can connect to the fake AP manually if browser is NOT launched - I get a notification that login might be neccesarry (Did not aknowledge authentication response - even though I click the message)
  - Phone gets disconnected but can't see the fake AP and still can use original AP for a short period of 
     time
  - Target tracker failed to unprep  error after some while
  
#### If the current behaviour is a bug, please provide the steps to reproduce it.
**HANDSHAKE**
1. Handshake retrieval: **aireplay-ng deauthentication (aggressive)**
2. Method of verification: **cowpatty verification (recommended)**
3. **Every 30 seconds**
4. **Synchronously (recommended).**

RESULT: **Success**

**CAPTIVE PORTAL**
1. Inteface: **wlan0    [*] Atheros Communications, Inc. AR9271 802.11n**
2. Interface for AP: **wlan0    [*] Atheros Communications, Inc. AR9271 802.11n**
3. AP service: **Rogue AP - hostapd (recommended)**
4. **Use hash found**
5. Method of verification: **cowpatty verification (recommended)**
6. SSL: **Create an SSL certificate**
7. Internet type: **disconnected (recommended)**
8. Captive portal interface: **[07] Generic Portal                                  English**

#### What do you think the expected behaviour should be?
All clients should be disconnected and lured into new-fake AP.

#### FLUXION Info
FLUXION V4.12

#### BASH Info 
GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.16.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-23)) #1 SMP Debian 4.16.16-2kali1 (2018-06-25)

**Comment by joker99789** [comment]
I have same issue

**Comment by deltaxflux** [comment]
Yeah, I will look at that today. I'm back :)

**Comment by deltaxflux** [comment]
Seems like issue is solved.

**Comment by MPX4132** [comment]
@mofox Is the issue fixed?

**Comment by mofox** [comment]
@MPX4132 Partially. I don't get the error message anymore, but the rest is still not working for me. I talked with deltaflux and I got stuck at mdk4 installation. I get an error message at "make" command. It's a bit harder for me, since I am a new Linux and Pentest user. I will report as soon as I make a live USB. I hope this weekend.

**Comment by deltaxflux** [comment]
@MPX4132 yeah I fixed this in the last commit.

**Comment by MPX4132** [comment]
@mofox Oh I see, if it's related to your build, it falls outside the bounds of fluxion.
@deltaxflux I see, I'll check it out to see what the issue was. I'm curious.

**Comment by moliata** [comment]
Not able to manually connect to an access point using same configuration as @mofox (without SSL cert).
